version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
      ember:
        patterns:
          - "ember-source"
          - "ember-cli"
      lint:
        patterns:
          - "@adfinis/eslint-config"
          - "@babel/eslint-parser"
          - "@commitlint*"
          - "@eslint/js"
          - "ember-template-lint*"
          - "eslint*"
          - "husky"
          - "lint-staged"
          - "prettier*"
          - "stylelint*"
